version: '3.1'

services:
  db:
    image: mysql:8.0.36
    container_name: gtbe
    environment:
      MYSQL_ROOT_PASSWORD: Toshiba_25
      MYSQL_DATABASE: gtbe
    ports:
      - "3069:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gtbe_pma
    environment:
      PMA_HOST: gtbe
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8083:80
volumes:
  dbdata: